config/routes.rb
Rails.application.routes.draw do
  root "chats#index"

  resources :chats, only: [:index, :new, :create, :show] do
    resources :messages, only: [:create]
  end

  get 'login', to: 'sessions#new', as: 'new_user_session'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
    has_many :users, through: :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index 
    @chats = Chat.all
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save 
      redirect_to chats_path
    else 
      render :new
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @messages = @chat.messages
    @message = Message.new
  end

  private

  def chat_params
    params.require(:chat).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def authenticate_user!
    redirect_to new_user_session_path unless current_user
  end

  def create
    @chat = Chat.find(params[:chat_id])
    @message = @chat.messages.new(message_params) 
    @message.user = current_user

    if @message.save
      Rails.logger.debug "Broadcasting with: #{render_message(@message)}"

      ActionCable.server.broadcast "chat_#{@chat.id}", {user: current_user.id, message: render_message(@message)}

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('messages', partial: 'messages/message', locals: { message: @message })
        end
        format.html { redirect_to @chat }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@message, partial: 'form', locals: { message: @message }), status: :unprocessable_entity
        end
        format.html { render 'chats/show', status: :unprocessable_entity }
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'messages/message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:email])

    if user #&& user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chats/index.html.erb
<h1>Chats</h1>

<div>
    <% @chats.each do |chat| %>
        <div>
            <%= link_to chat.name, chat_path(chat)%>
        </div>
    <% end %>
</div>

<h2>Create new chat:</h2>
<%= form_with(model: Chat.new, local: true) do |form|%>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.submit "Create" %>
    </div>
<% end %>

app/views/chats/show.html.erb
<h1><%= @chat.name %></h1>
<% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
    <ul>
    <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h2>Write message:</h2>
<%= form_with(model: [@chat, @message], local: false) do |form| %>
    <div>
        <%= form.label :content %>
        <%= form.text_area :content %>
    </div>

    <div>
        <%= form.submit "Send" %>
    </div>
<% end %>

<div id="messages">
    <% @messages&.each do |message| %>
        <%= render 'messages/message', message: message %>
    <% end %>
</div>

<div id="message-tooltip">!</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-user-id="<%= current_user&.id || 1 %>">
    <audio id="message-sound" preload="auto">
      <source src="<%= asset_path('beep.wav') %>" type="audio/wav">
      Your browser does not support the audio element.
    </audio>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message_<%= message.id %>">
    <p>
        <strong><%= message.user.name%></strong>
        <%= message.content%>
    </p>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>